export const ELEMENT_SELECTORS = {
  menuScreen: "#menu-screen",
  creationScreen: "#creation-screen",
  playScreen: "#play-screen",
  savesScreen: "#saves-screen",
  newVampireButton: "#new-vampire-button",
  menuContinueButton: "#menu-continue-button",
  menuContinueName: "#menu-continue-name",
  menuSavesButton: "#menu-saves-button",
  savesBackButton: "#saves-back-button",
  savesVampireList: "#saves-vampire-list",
  nameInput: "#name",
  identityMemoryInput: "#memory-identity",
  wizardHeaderName: "#wizard-header-name",
  creationBackButton: "#creation-back-button",
  wizardAvatarButton: "#wizard-avatar-button",
  stepProgress: "#step-progress",
  wizardStepLabel: "#wizard-step-label",
  stepProgressFill: "#step-progress-fill",
  backButton: "#back-button",
  nextButton: "#next-button",
  saveConfirmation: "#save-confirmation",
  mortalForm: "#mortal-form",
  mortalName: "#mortal-name",
  mortalDescription: "#mortal-description",
  mortalList: "#mortal-list",
  skillForm: "#skill-form",
  skillName: "#skill-name",
  skillDescription: "#skill-description",
  skillList: "#skill-list",
  resourceForm: "#resource-form",
  resourceName: "#resource-name",
  resourceDescription: "#resource-description",
  resourceList: "#resource-list",
  memoryFormLater: "#memory-form-later",
  memoryLater: "#memory-later",
  memoryTraitsLater: "#memory-traits-later",
  laterMemoryList: "#later-memory-list",
  immortalForm: "#immortal-form",
  immortalName: "#immortal-name",
  immortalDescription: "#immortal-description",
  immortalList: "#immortal-list",
  markForm: "#mark-form",
  markInput: "#mark-input",
  markDescription: "#mark-description",
  markList: "#mark-list",
  memoryFormCurse: "#memory-form-curse",
  memoryCurse: "#memory-curse",
  memoryTraitsCurse: "#memory-traits-curse",
  curseMemoryList: "#curse-memory-list",
  identityMemoryList: "#identity-memory-list",

  // Play screen shell
  playHeaderBack: "#play-header-back",
  playHamburgerButton: "#play-hamburger-button",
  playHeaderName: "#play-header-name",
  playAvatarButton: "#play-avatar-button",
  playMemoryDetailMoreButton: "#play-memory-detail-more",
  promptStampLabel: "#prompt-stamp-label",
  promptStatusLabel: "#prompt-status-label",
  promptButton: "#next-prompt-button",
  promptText: "#prompt-text",

  // Memories tab
  playTabMemories: "#play-tab-memories",
  memorySlotsMeta: "#memory-slots-meta",
  memorySlotsMoreButton: "#memory-slots-more-button",
  playMemoryListView: "#play-memory-list-view",
  playMemoryList: "#play-memory-list",
  playLostMemoryList: "#play-lost-memory-list",
  addMemoryButton: "#add-memory-button",
  playMemoryDetailView: "#play-memory-detail-view",
  playMemoryDetailTitle: "#play-memory-detail-title",
  playMemoryExperienceList: "#play-memory-experience-list",
  playExperienceForm: "#play-experience-form",
  playExperienceText: "#play-experience-text",
  playComposerColumns: "#play-composer-columns",
  playExperienceSubmit: "#play-experience-submit",
  playExperienceCancel: "#play-experience-cancel",

  // Traits tab
  playTabTraits: "#play-tab-traits",
  traitSortButton: "#trait-sort-button",
  playCharacterList: "#play-character-list",
  playSkillList: "#play-skill-list",
  playResourceList: "#play-resource-list",
  playMarkList: "#play-mark-list",
  addSkillButton: "#add-skill-button",
  addResourceButton: "#add-resource-button",
  addCharacterButton: "#add-character-button",
  addMarkButton: "#add-mark-button",

  // Diary tab
  playTabDiary: "#play-tab-diary",
  diaryEmptyState: "#diary-empty-state",
  createDiaryButton: "#create-diary-button",
  diaryCard: "#diary-card",
  diaryDescription: "#diary-description",
  diaryMemoryList: "#diary-memory-list",
  lostDiaryCard: "#lost-diary-card",
  lostDiaryMemoryList: "#lost-diary-memory-list",

  // Shared trait add/edit modal (reused for every "Edit" action)
  playSkillForm: "#play-skill-form",
  playSkillTitle: "#play-skill-form-title",
  playSkillName: "#play-skill-name",
  playSkillDescription: "#play-skill-description",
  playSkillSubmit: "#play-skill-submit",
  playSkillCancel: "#play-skill-cancel",
  playResourceForm: "#play-resource-form",
  playResourceTitle: "#play-resource-form-title",
  playResourceName: "#play-resource-name",
  playResourceDescription: "#play-resource-description",
  playResourceStationary: "#play-resource-stationary",
  playResourceSubmit: "#play-resource-submit",
  playResourceCancel: "#play-resource-cancel",
  playDiaryForm: "#play-diary-form",
  playDiaryDescription: "#play-diary-description",
  playDiarySubmit: "#play-diary-submit",
  playDiaryCancel: "#play-diary-cancel",
  playMemoryForm: "#play-memory-form",
  playMemoryTitle: "#play-memory-form-title",
  playMemoryExperienceFields: "#play-memory-experience-fields",
  playMemorySubmit: "#play-memory-submit",
  playMemoryCancel: "#play-memory-cancel",
  playCharacterForm: "#play-character-form",
  playCharacterTitle: "#play-character-form-title",
  playCharacterName: "#play-character-name",
  playCharacterDescription: "#play-character-description",
  playCharacterType: "#play-character-type",
  playCharacterSubmit: "#play-character-submit",
  playCharacterCancel: "#play-character-cancel",
  playMarkForm: "#play-mark-form",
  playMarkTitle: "#play-mark-form-title",
  playMarkName: "#play-mark-name",
  playMarkDescription: "#play-mark-description",
  playMarkSubmit: "#play-mark-submit",
  playMarkCancel: "#play-mark-cancel",
  playTraitModal: "#play-trait-modal",
  playModalTitle: "#play-modal-title",
};

export const getElements = () => {
  const elements = Object.fromEntries(
    Object.entries(ELEMENT_SELECTORS).map(([key, selector]) => [key, document.querySelector(selector)]),
  );
  return {
    ...elements,
    stepPanels: [...document.querySelectorAll("[data-step-panel]")],
    playBottomTabs: [...document.querySelectorAll("[data-play-tab]")],
    traitSubtabButtons: [...document.querySelectorAll("[data-trait-subtab]")],
    traitPanels: [...document.querySelectorAll("[data-trait-panel]")],
  };
};
